name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_PASSWORD_HASH_KEY: spice_uat
      REACT_APP_CRYPTR_SECRET_KEY: spice_uat
      REACT_APP_GA_TRACKING_ID: UA-220096139-1
      REACT_APP_ORG_SUCCESS_DELAY_TIME: 21000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Display npm version
        run: npm --version

      - name: Display Node.js version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Run tests and code coverage
        run: npm run test -- --coverage

      - name: List workspace contents
        run: ls -R

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=yohesh1197
            -Dsonar.projectKey=yohesh1197_open-source-new
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=*.test.{ts,tsx}
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}

